package-lock.json
package.json
src/app/test/GiyeonTest.tsx
src/app/test/HoyoungTest.tsx
src/app/test/HyeseonTest.tsx
src/app/test/KyungsuTest.tsx
src/app/test/YuseopTest.tsx
src/app/test/page.tsx
src/components/Button/button.tsx

- 기본 사이즈를 정하여 button 컴포넌트 제작했습니다. 페이지 작업 시 사이즈에 맞게 조정하면 될것같습니다.
- test폴더를 만들어 각자 테스트할수있게 페이지와 모듈생성을 했습니다. 사진처럼 각자 제작중인 컴포넌트를 확인해보시면 될것같습니다.

Feat(#06): 공통컴포넌트 button 컴포넌트 제작 , 테스트페이지 생성

---

src/components/Modal/ModalReviewAdd/ModalReviewAdd.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewFlavor.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewForm.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewHeader.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewRate.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewSmell.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewTextarea.tsx

- close #7
-모달 컴포넌트 작업하기 전에 파일 설정으로 충돌생길까봐 먼저 설정했습니다.

Feat(#7): modal 파일 설정

---

src/app/page.tsx
src/app/test/KyungsuTest.tsx
src/components/Card/Flavor/FlavorSlider.tsx

- close #4 
공통 컴포넌트 card-flavor 작업

Feat(#4): 공통 컴포넌트 card-flavor 작업

---

src/app/test/HyeseonTest.tsx
src/components/Input/(api)InputFile.tsx
src/components/Input/(api)InputProfileImage.tsx
src/components/Input/Input.tsx
src/components/Input/InputFile.tsx
src/components/Input/InputPassword.tsx
src/components/Input/InputProfileImage.tsx
src/components/Input/InputSearch.tsx
src/components/Input/InputSelect.tsx
src/components/Input/InputTextarea.tsx
src/components/Input/Label.tsx
src/components/Input/index.tsx

- #28 
- Input component 작업
- InputFile, InputProfileImg는 api 적용해서 수정해야 할 수도 있음

Feat(#28): Input 컴포넌트 생성

---

src/app/signin/page.tsx
src/app/test/HyeseonTest.tsx
src/components/Gnb/GnbLayout.tsx
src/components/Gnb/GnbUser.tsx
src/components/Gnb/Logo.tsx
src/components/Gnb/index.tsx

- #30 
- Gnb component 작업
- user 기능(로그인 상태 적용할 수 있는)을 추가해야 함
- dropdown 컴포넌트도 추가해야 함

Feat(#30): Gnb 컴포넌트 생성

---

src/app/test/HyeseonTest.tsx
src/components/Icon/ModalWineAdd/ModalWineAdd.tsx
src/components/Icon/ModalWineAdd/components/ModalWineAddHeader.tsx
src/components/Icon/ModalWineAdd/components/ModalWinedAddForm.tsx
src/components/Input/InputSelect.tsx
src/components/Modal/ModalWineAdd/ModalWineAdd.tsx
src/components/Modal/ModalWineAdd/components/ModalWineAddForm.tsx
src/components/Modal/ModalWineAdd/components/ModalWineAddHeader.tsx
src/components/Modal/ModalWineAdd/components/ModalWinedAddForm.tsx

- #10 
- ModalWineAdd 작업
- InputSelect 수정
- submit 부분 api post 요청 추가해야함
- file 부분도 api post 요청시 url 부분에 관한 코드 수정해야 함
- button cancel 배경 색 있는 버전으로 하나 더 추가 요청해야 함 -> 현재는 modalCancel에 강제로 배경색 적용시킴

Feat(#10): ModalWineAdd 생성(수정완료)

---

package-lock.json
package.json
src/app/test/KyungsuTest.tsx
src/components/Modal/ModalFilter/ModalFilter.tsx
src/components/filter/PriceSlider.tsx
src/components/filter/RatingFilter.tsx
src/components/filter/WineTypeSelector.tsx

Feat: 모달창  filter 작업

---

src/components/Modal/ModalReviewAdd/components/ModalReviewForm.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewSmell.tsx

- close #46
- smell 컴포넌트 작업.
- 선택한 태그의 향들을 Form컴포넌트에 전달할 수 있게 했습니다.
- 선택한 향들 state에 전달되는 것을 확인.

Feat(#46):모달/리뷰등록 Smell컴포넌트 완료

---

src/components/filter/PriceSlider.tsx
src/components/filter/RatingFilter.tsx

- close #57 
공통 컴포넌트 filter 에러 수정

Fix(#57): 공통 컴포넌트 filter 에러 수정

---

src/components/Modal/ModalReviewAdd/ModalReviewAdd.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewForm.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewRate.tsx

- close #51
- 모달 창에서 useParams를 사용하여 id를 얻고, id를 사용하여 와인의 name, image를 받아와 활용할 수 있게 prop으로 내려주었습니다.
- api 완성되면 제대로 작동하는지 테스트하고 다시 수정하겠습니다.

Feat(#51):modal review api

---

package-lock.json
src/app/test/dropdown/page.tsx
src/components/Dropdown/DropdownWithLinks.tsx
src/components/Dropdown/DropdownWithSelect.tsx
src/components/Dropdown/index.tsx

- #64 
- 드롭다운 컴포넌트 수정
- 드롭다운 컴포넌트 링크형, 선택형으로 나누어 작업
- 드롭다운 버튼 -> 부모에서 가져올 수 있게 함
- 테스트는 app/test/dropdown -> 호영님 테스트로 옮겨주시고 삭제해주시면 될 것 같습니다.

Fix(#64): 드롭다운 컴포넌트 수정

---

.gitignore
src/app/(auth)/oauth/callback/kakao/page.tsx
src/app/(auth)/oauth/signup/page.tsx
src/app/layout.tsx
src/components/Auth/SignInForm.tsx
src/components/Input/InputProfileImage.tsx
src/lib/api/auth.ts
src/lib/api/kakaoAuth.ts
src/lib/api/oauth.ts

- #72 
- signin 페이지에 카카오 로그인 연결

Feat(#72): SignIn - 카카오로그인연결

---

src/app/page.tsx
src/components/Auth/SignInForm.tsx
src/components/Auth/SignUpForm.tsx

- #78 
- 로그인, 회원가입시 enter 누름 -> 값이 유효함 -> 다음 필드로 넘어가도록 수정

Fix(#78): 로그인 회원가입 버그수정

---

src/app/test/KyungsuTest.tsx
src/components/Card/Monthly/MonthlyChart.tsx
src/components/Card/Wine/WineCard.tsx
src/components/Card/Wine/WineList.tsx

Feat(#62):컴포넌트 card wine

---

README.md
src/app/MetaTags.tsx
src/app/layout.tsx
src/app/metadata.ts
src/app/myprofile/components/MyProfile.tsx
src/app/myprofile/components/ProfileSetting.tsx
src/app/myprofile/components/TabButton.tsx
src/app/myprofile/components/TabContent.tsx
src/app/myprofile/components/TabCount.tsx
src/app/myprofile/layout.tsx
src/app/myprofile/page.tsx
src/app/not-found.tsx
src/app/test/HyeseonTest.tsx
src/app/test/wineadd/modalwineaddmode/page.tsx
src/app/test/wineadd/modalwineeditmode/page.tsx
src/app/test/wineadd/page.tsx
src/components/Card/Monthly/MonthlyChart.tsx
src/components/Gnb/GnbUser.tsx
src/components/Input/InputProfileImage.tsx
src/components/Modal/ModalWineAdd/ModalWineAdd.tsx
src/context/AuthProvider.tsx

- #95 
- 내 프로필 페이지 생성 (app/myprofile)
- 레이아웃(layout.tsx, page.tsx) 및 좌측 프로필 세팅 컴포넌트(app/myprofile/components/ProfileSetting.tsx) 작업
- README 초안 작성
- 메타 태그 설정
- 404 페이지 작업 완료
- 와인등록모달 등록/수정 모드 분리 테스트 
- 와인 등록 모달 테스트 : /test/wineadd
- 와인 등록 수정모드일때 와인 id 가져오는 부분은 다시 작성해야함 (현재는 수동으로 넣어놓고 테스트함)

Feat(#95): 내 프로필 페이지 레이아웃, 좌측 프로필 세팅 컴포넌트 작업 등

---

src/app/test/GiyeonTest.tsx
src/app/winelist/[id]/page.tsx
src/components/Modal/ModalReviewAdd/ModalReviewAdd.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewForm.tsx

- close #107 
- 리뷰모달 등록 및 삭제할때 재렌더링하여 리뷰목록을 자동적으로 업데이트 합니다.

Feat(#107): 리뷰모달 등록 및 삭제시 재렌더링

---

package-lock.json
src/app/winelist/[id]/page.tsx
src/components/Card/CardDetail.tsx

- close #109
- 와인 상세페이지 로드시 와인이 크게 보이는 것을 수정했습니다.

Refactor(#109): 와인상세페이지 로딩 작업

---

src/components/Modal/ModalReviewAdd/ModalReviewAdd.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewForm.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewHeader.tsx

- close #111
- 리뷰모달창의 제목이 리뷰 수정, 리뷰 등록으로 토글되게 수정.

Refactor(#111): 리뷰모달창 제목 토글

---

src/app/myprofile/components/TabContent.tsx
src/components/Card/Mylist/MyList.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewFlavor.tsx

- close #319 
- wine데이터를 프롭으로 받으면 카드를 보여주는 형식으로 작업했습니다.

feat(#113):공용 컴포넌트 cardmylist 컴포넌트 작업

---

src/components/Modal/ModalReviewAdd/ModalReviewAdd.tsx

- close #117 
-모달창을 열었을때 모달이 가장 z-index 우선되게 설정

Refactor(#117): 모달창을 열었을때 모달이 가장 z-index 우선되게 설정

---

src/components/Card/Flavor/FlavorSlider.tsx
src/components/Modal/ModalReviewAdd/ModalReviewAdd.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewFlavor.tsx

- close #119
- 화면 크기에 따라 리뷰모달창의 크기를 반응형으로 했습니다.

Feat(#119): 모달창 반응형 적용

---

src/app/winelist/[id]/layout.tsx
src/app/winelist/[id]/page.tsx
src/context/AuthProvider.tsx

- close #122
- 와인상세페이지 접근시 로그인 상태가 아니라면 로그인페이지로 리다이렉트

Feat(#121): 와인상세페이지 접근시 로그인 상태가 아니라면 로그인페이지로 리다이렉트

---

components.json
package-lock.json
package.json
src/app/winelist/[id]/layout.tsx
src/components/Card/Flavor/FlavorSlider.tsx
src/components/Modal/ModalReviewAdd/ModalReviewAdd.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewForm.tsx
src/components/Toast/Toast.tsx
src/components/ui/sonner.tsx
src/lib/utils.ts
src/styles/globals.css
tailwind.config.ts

- close #123 
- 리뷰 수정,생성했을때 토스트기능 추가

Feat(#123): shadcn라이브러리 사용하여 토스트 컴포넌트 추가

---

src/components/Modal/ModalReviewAdd/ModalReviewAdd.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewForm.tsx

Feat(#129):빌드 시 에러 수정

---

src/components/Card/CardReview/CardReview.tsx
src/components/Card/ProfileDisplay/ProfileDisplay.tsx

- close #319 
- 리뷰수정되었을때 (수정됨) 표시기능

Feat(#133): 리뷰수정되었을때 (수정됨) 표시기능

---

src/components/Modal/ModalReviewAdd/ModalReviewAdd.tsx

- close #135
- 리뷰등록 모달에 스크롤을 추가했습니다

Design: 리뷰 모달 스크롤 추가

---

src/app/page.tsx
src/components/Card/Wine/WineList.tsx
src/components/filter/RatingFilter.tsx

Design(#126): 렌딩페이지 반응형 추가

---

src/components/Modal/ModalReviewAdd/ModalReviewAdd.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewForm.tsx

- close #130
- 리뷰 수정, 생성시 뜨던 콘솔 오류를 해결했습니다.
- 리뷰 수정, 생성 실패시 토스트 알림을 추가했습니다.

Fix(#130): onSuccess 오류 수정 + 리뷰등록실패 Toast 추가

---

README.md
src/app/myprofile/components/ProfileSetting.tsx
src/app/myprofile/layout.tsx
src/app/test/wineadd/layout.tsx
src/app/test/wineadd/modalwineaddmode/page.tsx
src/app/test/wineadd/modalwineeditmode/page.tsx
src/components/Modal/ModalWineAdd/components/ModalWineAddForm.tsx
src/components/Toast/Toast.tsx

- #131  
- 마이프로필 - 프로필 세팅 부분 toast 적용
- toast width가 작아 글씨가 넘쳐서 글씨 크기, 패딩값으로 크기 조정함
-

Fix(#131) : toast 적용, README.md 추가

---

src/app/mypage/mypost/page.tsx
src/app/mypage/myreview/page.tsx
src/app/myprofile/components/MyReivews.tsx
src/components/Card/CardMyReview/CardMyReview.tsx
src/components/Card/Mylist/MyList.tsx
src/components/Card/ProfileDisplay/ProfileDisplay.tsx
src/components/Dropdown/index.tsx
src/components/Modal/ModalTwoButton/ModalTwoButton.tsx
src/components/Moremenu/MoreMenu.tsx

- close #146
- 마이프로필페이지 카드리스트 재렌더링 기능추가
- 삭제하기 modaltwobutton z-index 수정
- moremenu 드롭다운 스타일 수정
- 수정/삭제하기 토스트 사용

Fix(#146) 스타일링 및 오류 수정

---

src/components/Modal/ModalTwoButton/ModalTwoButton.tsx

fix(#150):build에러 수정

---

src/app/winelist/[id]/components/ReviewList.tsx
src/app/winelist/[id]/page.tsx
src/components/Modal/ModalReviewAdd/ModalReviewAdd.tsx
src/components/Modal/ModalReviewAdd/components/ModalReviewForm.tsx

- close #152 
- 리뷰생성 및 수정시 화면 새로고침
- 렌더링 방식으로 하고싶었는데 계속 에러나서 새로고침으로 구현했습니다...

Feat(#152): 리뷰생성 및 수정시 화면 새로고침

---

src/components/Card/Mylist/MyList.tsx

Fix(#153): mylist 가격 ui 크기조정

---

src/components/Card/Mylist/MyList.tsx

가격 ui 크기조정 (#156)
